development:
  adapter: postgresql
  encoding: unicode
  database: app_product_development
  pool: 5
  username: postgres
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: app_product_production
  pool: 5
  username: postgres
  password: root
  host: localhost